### ISSUE TITLE
Bump the Carbon Fields dependency

### ISSUE THREAD

**Issue by Jakob-Maudience** [htmlburger/carbon-fields-plugin#4]
Can the carbon fields version be bumped to the latest version (v3.1.8)? I think this plugin is about 5 versions behind.

**Comment by jorostoyanov** [comment]
Hi @Jakob-Maudience 

Thank you for pointing this out. The latest versions are now updated and can be downloaded from here: https://carbonfields.net/release-archive/

Cheers!

**Comment by Jakob-Maudience** [comment]
Thanks Joro!
