### ISSUE TITLE
image preview not working after update saving widget

### ISSUE THREAD

**Issue by rayhanuddin2019** [htmlburger/carbon-fields-plugin#6]
Hi 
      I created a widget with carbon fields where has a image field  like below image . after saving widget preview image not showing . Image working fine on frontend . Is there any solution for preview image . 

https://prnt.sc/shiwoa
Thanks

**Comment by jorostoyanov** [comment]
@rayhanuddin2019 This has been fixed in v3.2.0

Please update and feel free to re-open the issue if the problem persists :-)
