### ISSUE TITLE
support for composer/installers 2.0

### ISSUE THREAD

**Issue by AndPicc** [htmlburger/carbon-fields-plugin#8]
hello! 

the plugin requires composer/installers ^1.0 which is not compatible with composer 2.0 and therefore it's not possible to use composer 2.0 with this plugin.

is it possible to make it so that it supports both /installers ^1.0 || ^2.0 so then it can be used with composer 2 as well?

thanks!

**Comment by AndPicc** [comment]
Hello again!

I noticed that you've updated the plugin but it's still requiring composer/installers ^1.0

not sure why it hasn't been updated yet... is there a reason?

**Comment by HTMLBurger-NG** [comment]
Hi @AndPicc ,

Thank you for your feedback, we've updated the version in the `master` branch, we'll release the change with the next maintenance release of the `htmlburger/carbon-fields` library.
